### ISSUE TITLE
Does not work as expected 

### ISSUE THREAD

**Issue by piotrkochan** [gantsign/ansible-role-oh-my-zsh#109]
Simple role with username only installs zsh, oh-my-zsh but user to be able to 'use' oh-my-zsh must type zsh in the terminal anyway In fact zsh is being set as default shell as expected but still themes and other stuff not loading automatically.

Os: Ubuntu 20 Focal LTS

**Comment by 4F2E4A2E** [comment]
Hi there, for me it worked very well, here is how I did it:
## install

```bash
yum install sshpass -y
ansible-galaxy install gantsign.oh-my-zsh
```

## config

inventory
```yml
[centos_worker_1]
0.0.0.0

[centos_worker_1:vars]
ansible_host=0.0.0.0
ansible_connection=ssh
ansible_user=root
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
```

playbook
```yml
- hosts: centos_worker_1
  roles:
    - role: gantsign.oh-my-zsh
      users:
        - username: root
```

## run

```bash
ansible-playbook -c ssh --ask-pass -i inventory main.yml
```

The only thing not working are the themes. This is the message after the login:
```bash
/root/.oh-my-zsh/oh-my-zsh.sh:source:128: no such file or directory: /root/.oh-my-zsh/themes/Powerlevel9k.zsh-theme
``` 

Os: CentOs 8

**Comment by piotrkochan** [comment]
It works, it was just another weird wsl issue
