### ISSUE TITLE
Feature Request: Custom plugin installation

### ISSUE THREAD

**Issue by oncleben31** [gantsign/ansible-role-oh-my-zsh#117]
Hello what do you think about adding a way to install custom plugins ?

Generally it means:
 - clone a git repository in ~/.oh-my-zsh/custom/plugins
 - add an entry in the `plugins` list

**Comment by oncleben31** [comment]
A quick and dirty implementation prototype: https://github.com/oncleben31/infra/commit/8da46ae2edcfe1e9d0c846576263dccb19380db8

If you are interested, I can work on a PR.

**Comment by freemanjp** [comment]
@oncleben31 I appreciate the suggestion, but once you start installing custom plugins, you're better off using a Zsh plugin manager such as [Antigen](https://github.com/zsh-users/antigen), which his why I created an Ansible role for Antigen [gantsign.antigen](https://github.com/gantsign/ansible_role_antigen). You can use it to install Oh My Zsh and custom plugins. I suggest you check it out.

**Comment by oncleben31** [comment]
I didn't know Antigen before this issue. I gave a try and honestly I'm a bit frustrated with this approach despite being very promising.

My previous approach based on ansible-role-oh-my-zsh and the one base on  gantsign.antigen where in conflict. And trying to start from scratch I have difficulties to have a a clean installation (still have issues with theme).

And what about maintenance of the Ansible Role and Antigen repo. The fact there is no recent release make me hesitate to deepdive in this approach.

**Comment by freemanjp** [comment]
There's a bunch of other Zsh plugin managers (see https://github.com/unixorn/awesome-zsh-plugins#installation), most of which have more features and faster loading times than Oh My Zsh's plugin handling. Honestly, if I were starting from scratch, I'd probably use [prezto](https://github.com/sorin-ionescu/prezto) or [zplug](https://github.com/zplug/zplug) (I don't know if there are Ansible roles for either of them), but Antigen has been working well for me for years.

If you still want to use Oh My Zsh for plugin management you're welcome to fork this role (that's part of the reason it's MIT licensed). I'll probably deprecate this role at some point, I've not used it in years, the only reason I haven't is it's still widely used and requires little maintenance.

**Comment by oncleben31** [comment]
Thank you for the discussion. I will keep my quick @ dirty custom plugin management in Oh My Zsh.
And look for implementing alternatives in the future.
