### ISSUE TITLE
Add option to skip default .zshrc file creation

### ISSUE THREAD

**Issue by DavidGL17** [gantsign/ansible-role-oh-my-zsh#160]
Hi,

I've been using your role and have had no issue, but I have a possible upgrade that could be made : 

A boolean could be added to skip the default .zshrc file creation on install. Currently, when i rerun the playbook I have that uses this role this task is always marked as changed because I put my own custom .zshrc file later, and it would be nice if this small change could be added.

Kind regards,

David

**Comment by YacineSahli** [comment]
Hi, u should move ur custom config in the ./oh-my-zsh/custom/   folder.

**Comment by mircsicz** [comment]
Can u please be specific about the path of that folder?

I've been looking in roles/gantsign.oh-my-zsh but can't find it there...

**Comment by freemanjp** [comment]
@DavidGL17 thanks for raising this issue, a flag to control this behavior has been added in version [2.7.0](https://github.com/gantsign/ansible-role-oh-my-zsh/releases/tag/2.7.0) of this role.

**Comment by DavidGL17** [comment]
Thank you very much for your work, sorry for not giving any answers after my question i was a bit occupied these last few weeks ^^
