### ISSUE TITLE
Temp file issues

### ISSUE THREAD

**Issue by jgeusebroek** [gantsign/ansible-role-oh-my-zsh#80]
I have been using your role for quite a while, thanks!

I've ran into some troubles with the latest version. At first I thought it was Ansible 2.7 that caused it, but that is unrelated (I updated but Ansible and the role at the same time). In the end I downgrade to a previous version of the role and it worked fine again.

d888ed42bea294831646b07a097cde8a9cab794b

`TASK [gantsign.oh-my-zsh : clone oh-my-zsh for users] ************************************************************************************************************************************************************

ok: [x.lan] => (item={u'username': u'user', u'oh_my_zsh': {u'theme': u'robbyrussell', u'plugins': [u'git', u'docker', u'cpv', u'copydir', u'copyfile', u'zsh-syntax-highlighting']}})
 [WARNING]: Module remote_tmp /home/docker/.ansible/tmp did not exist and was created with a mode of 0700, this may cause issues when running as another user. To avoid this, create the remote_tmp dir with the
correct permissions manually`

And later on:

`TASK [gantsign.oh-my-zsh : write .zshrc for users] ***************************************************************************************************************************************************************

changed: [x.lan] => (item={u'username': u'user', u'oh_my_zsh': {u'theme': u'robbyrussell', u'plugins': [u'git', u'docker', u'cpv', u'copydir', u'copyfile', u'zsh-syntax-highlighting']}})
fatal: [x.lan]: FAILED! => {"msg": "Failed to set permissions on the temporary files Ansible needs to create when becoming an unprivileged user (rc: 1, err: chown: changing ownership of '/var/tmp/ansible-tmp-1538996917.56-214497945895580/': Operation not permitted\nchown: changing ownership of '/var/tmp/ansible-tmp-1538996917.56-214497945895580/source': Operation not permitted\n}). For information on working around this, see https://docs.ansible.com/ansible/become.html#becoming-an-unprivileged-user"}`

**Comment by freemanjp** [comment]
I don't think the problem you're encountering is a problem with the role itself. The diff you've linked to is a documentation change to the `README.md` so won't affect the functioning of this role. This role doesn't create the directory `/home/docker/.ansible/tmp` so isn't responsible for the file permissions/mode. It also doesn't attempt to change the permissions for `/var/tmp/ansible-tmp-1538996917.56-214497945895580/source`.

I'm guessing it's some sort of permissions issue related to the way you're running Ansible.

**Comment by jgeusebroek** [comment]
Thanks for the reply. Actually that's what I thought also, the strange thing is though that downgrading actually results in no issues at all.

I'll have a look when I have some time to spend. Should I find something, I'll let you know. Thanks.
